name: CI

on:
  push:
    branches: [ "main", "dev"]
  pull_request:
    branches: [ "main" ]

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
    - run: echo test1
  test2:
    runs-on: ubuntu-latest
    steps:
    - run: echo test2
  test3:
    runs-on: ubuntu-latest
    steps:
    - run: echo test3
