name: workflow2

on:
  workflow_run:
    workflows: ["workflow1"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: build
        run: echo workflow22 ${{secrets.PASSWORD}}
